import{useRef,useState}from"react";import{AnimatePresence,motion}from"framer-motion";import{Music,Music2}from"lucide-react";import{weddingData as d}from"./weddingData";import Opening from"./components/Opening";import Countdown from"./components/Countdown";
export default function App(){const[o,setO]=useState(false),[p,setP]=useState(false),a=useRef(null);const open=async()=>{setO(true);try{await a.current?.play();setP(true)}catch{setP(false)}};const music=async()=>{if(!a.current)return;if(a.current.paused){try{await a.current.play();setP(true)}catch{}}else{a.current.pause();setP(false)}};
return <main><audio ref={a} src="/music/wedding-song.mp3" loop preload="auto"/><AnimatePresence>{!o&&<Opening onOpen={open}/>}</AnimatePresence>{o&&<motion.div initial={{opacity:0}} animate={{opacity:1}}>
<section className="screen intro"><div className="content"><p className="mantra">॥ श्री गणेशाय नमः ॥</p><div className="om">ॐ</div><p className="label">श्री राम की कृपा से</p><h1>मंगल परिणयोत्सव</h1><div className="divider">❦</div><p className="bigcopy">हमारे परिवार में शुभ विवाह का<br/>मंगल अवसर आया है</p><p className="date">{d.date}</p><a href="#couples" className="down">मंगल यात्रा आरंभ करें<br/>⌄</a></div></section>
<div id="couples">{d.couples.map((c,i)=><section className="screen couple" key={c.groom}><motion.div className="content coupleBox" initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="label">शुभ विवाह</p><small>मंगल मिलन • {i?"द्वितीय":"प्रथम"}</small><h2>✦ {c.groom} ✦</h2><p className="sang">संग</p><h2>✦ {c.bride} ✦</h2><div className="divider">❦</div><p className="bigcopy">{c.line}</p></motion.div></section>)}</div>
<section className="screen brothers"><div className="content"><div className="orn">❦</div><h1>एक आँगन, दो खुशियाँ</h1><div className="divider">✦</div><p className="bigcopy">दो भाइयों के जीवन में<br/>आरंभ हो रहा है एक नया अध्याय</p><h2>मौसम ❦ वतन</h2><p className="bigcopy">आपके स्नेह और आशीर्वाद की<br/>हमें प्रतीक्षा रहेगी</p></div></section>
<Countdown targetDate={d.dateISO}/>
<section className="events"><div className="content"><p className="label">वैवाहिक कार्यक्रम</p><h1>शुभ कार्यक्रम</h1><div className="divider">❦</div><div className="timeline">{d.events.map((e,i)=><motion.article key={e.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><b>{e.symbol}</b><div><h3>{e.title}</h3><p>{e.date}</p><span>{e.time}</span></div></motion.article>)}</div></div></section>
<section className="screen venue"><div className="content frame"><p className="label">पधारो सा</p><h1>{d.venue.name}</h1><div className="divider">✦</div><p className="bigcopy">{d.venue.address}</p><a className="btn" href={d.venue.mapUrl} target="_blank" rel="noreferrer">📍 दिशा निर्देश देखें</a></div></section>
<footer className="screen footer"><div className="content"><div className="om">ॐ</div><h1>आपकी उपस्थिति ही<br/>हमारा सौभाग्य है</h1><div className="divider">❦</div><p className="bigcopy">{d.invitation}</p><h3>{d.family}</h3><p>।। शुभ विवाह ।।</p><button className="btn light" onClick={async()=>{const x={title:"Mousame & Vatan Wedding",text:"सैनी परिवार की ओर से स्नेह निमंत्रण",url:location.href};if(navigator.share)await navigator.share(x);else{await navigator.clipboard.writeText(location.href);alert("निमंत्रण लिंक कॉपी हो गया")}}}>निमंत्रण साझा करें</button></div></footer>
<button className="music" onClick={music}>{p?<Music size={21}/>:<Music2 size={21}/>}</button></motion.div>}</main>}